imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: TUTORDIRSESSID
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ FitchFrontEndBundle, FitchTutorBundle ]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        cssembed:
            jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        sass:    ~
        compass:
            bin: %compass_bin%
            http_fonts_path: "/bundles/fitchfrontend/fonts"
    assets:
        jquery_js:
            inputs:
                - '%kernel.root_dir%/../components/jquery/jquery.js'
            filters: [?yui_js]
        datatable_js:
            inputs:
#                - '%kernel.root_dir%/../components/moment/moment.js'
                - '%kernel.root_dir%/../vendor/datatables/datatables/media/js/jquery.dataTables.js'
                - '@FitchFrontEndBundle/Resources/assets/js/dataTables.bootstrap.js'
                - '@FitchFrontEndBundle/Resources/assets/js/jquery.highlight.js'
                - '%kernel.root_dir%/../vendor/drmonty/datatables-tabletools/js/dataTables.tableTools.min.js'
            filters: [?yui_js]
        jqueryui_js:
            inputs:
                - '%kernel.root_dir%/../components/jquery-ui/jquery-ui.js'
            filters: [?yui_js]
        underscore_js:
            inputs:
                - '%kernel.root_dir%/../components/underscore/underscore.js'
            filters: [?yui_js]
        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/transition.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/alert.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/modal.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/dropdown.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/scrollspy.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/tab.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/tooltip.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/popover.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/button.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/collapse.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/carousel.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/affix.js'
            filters: [?yui_js]
        frontend_js:
            inputs:
                - '@FitchFrontEndBundle/Resources/assets/js/jquery-plugin.js'
                - '@FitchFrontEndBundle/Resources/assets/js/main-navigation.js'
                - '@FitchFrontEndBundle/Resources/assets/js/resize.js'
                - '@FitchFrontEndBundle/Resources/assets/js/autosize.js'
                - '@FitchFrontEndBundle/Resources/assets/js/widget.js'
                - '@FitchFrontEndBundle/Resources/assets/js/generic-field-ajax.js'
                - '@FitchFrontEndBundle/Resources/assets/js/generic-div-ajax.js'
                - '@FitchFrontEndBundle/Resources/assets/js/bootstrap-multiselect.js'
                - '@FitchFrontEndBundle/Resources/assets/js/bootstrap-editable.js'
                - '@FitchFrontEndBundle/Resources/assets/js/summernote.js'
                - '@FitchFrontEndBundle/Resources/assets/js/dropzone.js'
                - '@FitchFrontEndBundle/Resources/assets/js/jquery.jcrop.js'
                - '@FitchFrontEndBundle/Resources/assets/js/jquery.simplecolorpicker.js'
                - '@FitchFrontEndBundle/Resources/assets/js/jquery.typeahead.js'
                - '@FitchFrontEndBundle/Resources/assets/js/typeaheadjs.js'
            filters: [?yui_js]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                is_bundle: false


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUserBundle configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Fitch\UserBundle\Entity\User
    profile:
        form:
            type: fitch_user_registration

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            timestampable: true
            loggable: true

oneup_uploader:
    mappings:
        tutor:
            frontend: dropzone
            storage:
              type: gaufrette
              filesystem: gaufrette.tutor_filesystem
              sync_buffer_size: 1M

knp_gaufrette:
    adapters:
        tutor:
            amazon_s3:
                amazon_s3_id:   amazonS3
                bucket_name:    %aws_bucket%
                options:
                    directory:  %aws_file_directory%

    filesystems:
        tutor:
            adapter: tutor

    stream_wrapper: ~

services:
    introspection_service:
        class: Monolog\Processor\IntrospectionProcessor
        tags:
            - { name: monolog.processor }
    psr3_service:
        class: Monolog\Processor\PsrLogMessageProcessor
        tags:
            - { name: monolog.processor }
    pid_service:
        class: Monolog\Processor\ProcessIdProcessor
        tags:
            - { name: monolog.processor }
    twig.extension.text:
            class: Twig_Extensions_Extension_Text
            tags:
                - { name: twig.extension }
    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
             - { name: 'twig.extension' }
