security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        # UI Visibility Roles
        ROLE_CAN_ACCESS_SIDEBAR: ~

        # Task based roles
        ROLE_CAN_VIEW_TUTOR: ~
        ROLE_CAN_EDIT_TUTOR: ROLE_CAN_VIEW_TUTOR
        ROLE_CAN_CREATE_TUTOR: ROLE_CAN_EDIT_TUTOR
        ROLE_CAN_ACCESS_SENSITIVE_DATA: ROLE_CAN_VIEW_TUTOR

        ROLE_CAN_EDIT_LOOKUP_VALUES: [ROLE_CAN_ACCESS_SIDEBAR]
        ROLE_CAN_CREATE_LOOKUP_VALUES: ~

        ROLE_CAN_VIEW_SAVED_REPORTS: ~
        ROLE_CAN_CREATE_AD_HOC_REPORTS: ~
        ROLE_CAN_CREATE_SAVED_REPORTS: [ROLE_CAN_CREATE_AD_HOC_REPORTS, ROLE_CAN_VIEW_SAVED_REPORTS, ROLE_CAN_ACCESS_SIDEBAR]

        ROLE_CAN_MANAGE_USERS: [ROLE_CAN_ACCESS_SIDEBAR]

        ## User Assigned roles
        ROLE_USER: [ROLE_CAN_VIEW_TUTOR, ROLE_CAN_VIEW_SAVED_REPORTS]
        ROLE_SENSITIVE_DATA: [ROLE_USER, ROLE_CAN_ACCESS_SENSITIVE_DATA]
        ROLE_EDITOR: [ROLE_CAN_CREATE_TUTOR, ROLE_CAN_CREATE_SAVED_REPORTS]
        ROLE_ADMIN: [ROLE_EDITOR, ROLE_SENSITIVE_DATA, ROLE_CAN_EDIT_LOOKUP_VALUES, ROLE_CAN_CREATE_LOOKUP_VALUES]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_CAN_MANAGE_USERS]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
            logout:       true
            anonymous:    true
            switch_user: { role: ROLE_SUPER_ADMIN, parameter: _impersonate }
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
# disable register by it available only to super admins
        - { path: ^/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: ROLE_USER }
        - { path: ^/profile, role: ROLE_USER }
        - { path: ^/editor, role: ROLE_EDITOR }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/user, role: ROLE_SUPER_ADMIN }
        - { path: ^/report, role: ROLE_USER }

