parameters:
#    fitch_common.example.class: Fitch\CommonBundle\Example

services:
#    fitch_common.example:
#        class: %fitch_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
