<?php

namespace Fitch\TutorBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
}
