parameters:
  fitch.manager.tutor.class: Fitch\TutorBundle\Model\TutorManager
  fitch.manager.phone.class: Fitch\TutorBundle\Model\PhoneManager
  fitch.manager.email.class: Fitch\TutorBundle\Model\EmailManager
  fitch.manager.file.class: Fitch\TutorBundle\Model\FileManager
  fitch.manager.file_type.class: Fitch\TutorBundle\Model\FileTypeManager
  fitch.manager.operating_region.class: Fitch\TutorBundle\Model\OperatingRegionManager
  fitch.manager.country.class: Fitch\TutorBundle\Model\CountryManager
  fitch.manager.competency.class: Fitch\TutorBundle\Model\CompetencyManager
  fitch.manager.competency_type.class: Fitch\TutorBundle\Model\CompetencyTypeManager
  fitch.manager.competency_level.class: Fitch\TutorBundle\Model\CompetencyLevelManager
  fitch.manager.address.class: Fitch\TutorBundle\Model\AddressManager
  fitch.manager.status.class: Fitch\TutorBundle\Model\StatusManager
  fitch.manager.tutor_type.class: Fitch\TutorBundle\Model\TutorTypeManager
  fitch.manager.currency.class: Fitch\TutorBundle\Model\CurrencyManager
  fitch.manager.note.class: Fitch\TutorBundle\Model\NoteManager
  fitch.manager.crop_info.class: Fitch\TutorBundle\Model\CropInfoManager
  fitch.manager.rate.class: Fitch\TutorBundle\Model\RateManager
  fitch.manager.language.class: Fitch\TutorBundle\Model\LanguageManager
  fitch.manager.tutor_language.class: Fitch\TutorBundle\Model\TutorLanguageManager
  fitch.manager.report.class: Fitch\TutorBundle\Model\ReportManager
  fitch.manager.category.class: Fitch\TutorBundle\Model\CategoryManager

  fitch.entity.tutor.class: Fitch\TutorBundle\Entity\Tutor
  fitch.entity.phone.class: Fitch\TutorBundle\Entity\Phone
  fitch.entity.email.class: Fitch\TutorBundle\Entity\Email
  fitch.entity.file.class: Fitch\TutorBundle\Entity\File
  fitch.entity.file_type.class: Fitch\TutorBundle\Entity\FileType
  fitch.entity.operating_region.class: Fitch\TutorBundle\Entity\OperatingRegion
  fitch.entity.country.class: Fitch\TutorBundle\Entity\Country
  fitch.entity.competency.class: Fitch\TutorBundle\Entity\Competency
  fitch.entity.competency_type.class: Fitch\TutorBundle\Entity\CompetencyType
  fitch.entity.competency_level.class: Fitch\TutorBundle\Entity\CompetencyLevel
  fitch.entity.address.class: Fitch\TutorBundle\Entity\Address
  fitch.entity.status.class: Fitch\TutorBundle\Entity\Status
  fitch.entity.tutor_type.class: Fitch\TutorBundle\Entity\TutorType
  fitch.entity.currency.class: Fitch\TutorBundle\Entity\Currency
  fitch.entity.note.class: Fitch\TutorBundle\Entity\Note
  fitch.entity.crop_info.class: Fitch\TutorBundle\Entity\CropInfo
  fitch.entity.rate.class: Fitch\TutorBundle\Entity\Rate
  fitch.entity.language.class: Fitch\TutorBundle\Entity\Language
  fitch.entity.tutor_language.class: Fitch\TutorBundle\Entity\TutorLanguage
  fitch.entity.report.class: Fitch\TutorBundle\Entity\Report
  fitch.entity.category.class: Fitch\TutorBundle\Entity\Category

services:
    #
    # Model Managers
    #
    fitch.manager.tutor:
        class: %fitch.manager.tutor.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.tutor.class%
    fitch.manager.phone:
        class: %fitch.manager.phone.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.phone.class%
    fitch.manager.email:
        class: %fitch.manager.email.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.email.class%
    fitch.manager.file:
        class: %fitch.manager.file.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.file.class%
    fitch.manager.file_type:
        class: %fitch.manager.file_type.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.file_type.class%
    fitch.manager.competency:
        class: %fitch.manager.competency.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.competency.class%
    fitch.manager.competency_level:
        class: %fitch.manager.competency_level.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.competency_level.class%
    fitch.manager.competency_type:
        class: %fitch.manager.competency_type.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.competency_type.class%
    fitch.manager.country:
        class: %fitch.manager.country.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.country.class%
    fitch.manager.operating_region:
        class: %fitch.manager.operating_region.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.operating_region.class%
    fitch.manager.address:
        class: %fitch.manager.address.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.address.class%
    fitch.manager.status:
        class: %fitch.manager.status.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.status.class%
    fitch.manager.tutor_type:
        class: %fitch.manager.tutor_type.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.tutor_type.class%
    fitch.manager.currency:
        class: %fitch.manager.currency.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.currency.class%
    fitch.manager.note:
        class: %fitch.manager.note.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.note.class%
    fitch.manager.crop_info:
        class: %fitch.manager.crop_info.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.crop_info.class%
    fitch.manager.rate:
        class: %fitch.manager.rate.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.rate.class%
    fitch.manager.language:
        class: %fitch.manager.language.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.language.class%
    fitch.manager.tutor_language:
        class: %fitch.manager.tutor_language.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.tutor_language.class%
    fitch.manager.report:
        class: %fitch.manager.report.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.report.class%
    fitch.manager.category:
        class: %fitch.manager.category.class%
        calls:
            - [setLogger, ["@logger"]]
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %fitch.entity.category.class%

#
# Event Listener
#

    fitch.upload_listener:
        class: Fitch\TutorBundle\Listener\UploadListener
        arguments:
            tutorManager: "@fitch.manager.tutor"
            fileManager: "@fitch.manager.file"
            fileTypeManager: "@fitch.manager.file_type"
            templating: "@templating"
            container: "@service_container"
        tags:
            - {name: kernel.event_listener, event: oneup_uploader.pre_upload, method: onPreUpload}
            - {name: kernel.event_listener, event: oneup_uploader.post_persist, method: onPostPersist}
### We have to inject the wole container here, and use its lazy loading to get to the security context inside the
### listener. This is fixed in symfony2.6 which isnt available at the time of writing. In 2.6 we can just inject
### "@security.token_storage" rather than the whole container. If you are reading this after 2.6 is released please
### make the approprate change.

#
# Security Voter
#
    security.access.tutor_voter:
        class:      Fitch\TutorBundle\Security\Authorization\Voter\TutorVoter
        public:     false
        arguments: ['%security.role_hierarchy.roles%']
        tags:
           - { name: security.voter }

#
# Amazon S3 Bucket
#
    amazonS3:
        class: AmazonS3
        arguments:
            options:
                key:      '%aws_key%'
                secret:   '%aws_secret_key%'
