<?php

namespace Fitch\TutorBundle\Model;

use Fitch\CommonBundle\Model\BaseModelManager;
use Fitch\TutorBundle\Entity\Repository\AddressRepository;
use Fitch\TutorBundle\Entity\Address;

class AddressManager extends BaseModelManager implements AddressManagerInterface
{
    /**
     * @param int $id
     */
    public function removeEntity($id)
    {
        $address = $this->findById($id);
        parent::removeEntity($address);
    }

    /**
     * Used  to identify logs generated by this class.
     *
     * @return string
     */
    protected function getDebugKey()
    {
        return 'fitch.manager.address';
    }
}
