<?php

namespace Fitch\TutorBundle\Model;

use Fitch\CommonBundle\Model\BaseModelManager;
use Fitch\TutorBundle\Entity\Repository\CompetencyRepository;
use Fitch\TutorBundle\Entity\Competency;
use Fitch\TutorBundle\Entity\Tutor;

class CompetencyManager extends BaseModelManager implements CompetencyManagerInterface
{
    /**
     * @inherit
     *
     * @param $id
     * @param Tutor $tutor
     *
     * @return Competency
     */
    public function findOrCreateCompetency($id, Tutor $tutor)
    {
        if ($id) {
            $competency = $this->findById($id);
        } else {
            $competency = $this->createEntity();
            $tutor->addCompetency($competency);
        }

        return $competency;
    }

    /**
     * Used  to identify logs generated by this class.
     *
     * @return string
     */
    protected function getDebugKey()
    {
        return 'fitch.manager.competency';
    }
}
