<?php

namespace Fitch\TutorBundle\Model;

use Fitch\CommonBundle\Exception\EntityNotFoundException;
use Fitch\CommonBundle\Model\BaseModelManager;
use Fitch\TutorBundle\Entity\Repository\CropInfoRepository;
use Fitch\TutorBundle\Entity\CropInfo;

class CropInfoManager extends BaseModelManager
{
   /**
     * @param $id
     * @throws EntityNotFoundException
     * @return CropInfo
     */
    public function findById($id)
    {
        return parent::findById($id);
    }

    /**
     * @return CropInfo[]
     */
    public function findAll()
    {
        return parent::findAll();
    }

    /**
     * @param CropInfo $cropInfo
     * @param bool $withFlush
     */
    public function saveCropInfo($cropInfo, $withFlush = true)
    {
        parent::saveEntity($cropInfo, $withFlush);
    }

    /**
     * Create a new CropInfo
     *
     * Set its default values
     *
     * @return CropInfo
     */
    public function createCropInfo()
    {
        return parent::createEntity();
    }

    /**
     * @param int $id
     */
    public function removeCropInfo($id)
    {
        $cropInfo = $this->findById($id);
        parent::removeEntity($cropInfo);
    }

    /**
     * @param CropInfo $cropInfo
     */
    public function refreshCropInfo(CropInfo $cropInfo)
    {
        parent::reloadEntity($cropInfo);
    }

    /**
     * @return CropInfoRepository
     */
    private function getRepo()
    {
        return $this->repo;
    }

    /**
     * Used  to identify logs generated by this class
     *
     * @return string
     */
    protected function getDebugKey()
    {
        return 'fitch.manager.crop_info';
    }
}
