<?php

namespace Fitch\TutorBundle\Model;

use Fitch\CommonBundle\Exception\EntityNotFoundException;
use Fitch\CommonBundle\Model\BaseModelManager;
use Fitch\TutorBundle\Entity\Repository\CropInfoRepository;
use Fitch\TutorBundle\Entity\CropInfo;

class CropInfoManager extends BaseModelManager implements CropInfoManagerInterface
{
    /**
     * Used  to identify logs generated by this class.
     *
     * @return string
     */
    protected function getDebugKey()
    {
        return 'fitch.manager.crop_info';
    }
}
