<?php

namespace Fitch\TutorBundle\Model;

use Fitch\CommonBundle\Exception\EntityNotFoundException;
use Fitch\CommonBundle\Model\BaseModelManager;
use Fitch\TutorBundle\Entity\Repository\CurrencyRepository;
use Fitch\TutorBundle\Entity\Currency;

class CurrencyManager extends BaseModelManager
{
    /**
     * @param $id
     * @throws EntityNotFoundException
     * @return Currency
     */
    public function findById($id)
    {
        return parent::findById($id);
    }

    /**
     * @return Currency[]
     */
    public function findAll()
    {
        return parent::findAll();
    }

    /**
     * @return Currency[]
     */
    public function findAllSorted()
    {
        return $this->getRepo()->findBy([],  array('preferred' => 'DESC', 'name' => 'ASC'));
    }

    /**
     * @return Currency
     */
    public function getDefaultCurrency()
    {
        return $this->getRepo()->findOneBy(['threeDigitCode' => 'GBP']);
    }

    /**
     * @param Currency $currency
     * @param bool $withFlush
     */
    public function saveCurrency($currency, $withFlush = true)
    {
        parent::saveEntity($currency, $withFlush);
    }

    /**
     * Create a new Currency
     *
     * Set its default values
     *
     * @return Currency
     */
    public function createCurrency()
    {
        return parent::createEntity();
    }

    /**
     * @param int $id
     */
    public function removeCurrency($id)
    {
        $currency = $this->findById($id);
        parent::removeEntity($currency);
    }

    /**
     * @param Currency $currency
     */
    public function refreshCurrency(Currency $currency)
    {
        parent::reloadEntity($currency);
    }

    /**
     * @return CurrencyRepository
     */
    private function getRepo()
    {
        return $this->repo;
    }

    /**
     * Used  to identify logs generated by this class
     *
     * @return string
     */
    protected function getDebugKey()
    {
        return 'fitch.manager.currency';
    }
}
