<?php

namespace Fitch\TutorBundle\Model;

use Fitch\CommonBundle\Exception\EntityNotFoundException;
use Fitch\CommonBundle\Model\BaseModelManager;
use Fitch\TutorBundle\Entity\Repository\FileRepository;
use Fitch\TutorBundle\Entity\File;

class FileManager extends BaseModelManager
{
   /**
     * @param $id
     * @throws EntityNotFoundException
     * @return File
     */
    public function findById($id)
    {
        return parent::findById($id);
    }

    /**
     * @return File[]
     */
    public function findAll()
    {
        return parent::findAll();
    }

    /**
     * @param File $file
     * @param bool $withFlush
     */
    public function saveFile($file, $withFlush = true)
    {
        parent::saveEntity($file, $withFlush);
    }

    /**
     * Create a new File
     *
     * Set its default values
     *
     * @return File
     */
    public function createFile()
    {
        return parent::createEntity();
    }

    /**
     * @param int $id
     */
    public function removeFile($id)
    {
        $file = $this->findById($id);
        parent::removeEntity($file);
    }

    /**
     * @param File $file
     */
    public function refreshFile(File $file)
    {
        parent::reloadEntity($file);
    }

    /**
     * @return FileRepository
     */
    private function getRepo()
    {
        return $this->repo;
    }

    /**
     * Used  to identify logs generated by this class
     *
     * @return string
     */
    protected function getDebugKey()
    {
        return 'fitch.manager.file';
    }
}
