<?php

namespace Fitch\TutorBundle\Model;

use Fitch\CommonBundle\Exception\EntityNotFoundException;
use Fitch\CommonBundle\Model\BaseModelManager;
use Fitch\TutorBundle\Entity\Repository\NoteRepository;
use Fitch\TutorBundle\Entity\Note;
use Fitch\TutorBundle\Model\NoteManagerInterface;

class NoteManager extends BaseModelManager implements NoteManagerInterface
{
    /**
     * @param $id
     *
     * @throws EntityNotFoundException
     *
     * @return Note
     */
    public function findById($id)
    {
        return parent::findById($id);
    }

    /**
     * @return Note[]
     */
    public function findAll()
    {
        return parent::findAll();
    }

    /**
     * @param Note $note
     * @param bool $withFlush
     */
    public function saveNote($note, $withFlush = true)
    {
        parent::saveEntity($note, $withFlush);
    }

    /**
     * Create a new Note.
     *
     * Set its default values
     *
     * @return Note
     */
    public function createNote()
    {
        return parent::createEntity();
    }

    /**
     * @param int $id
     */
    public function removeNote($id)
    {
        $note = $this->findById($id);
        parent::removeEntity($note);
    }

    /**
     * @param Note $note
     */
    public function refreshNote(Note $note)
    {
        parent::reloadEntity($note);
    }

    /**
     * @return NoteRepository
     */
    private function getRepo()
    {
        return $this->repo;
    }

    /**
     * Used  to identify logs generated by this class.
     *
     * @return string
     */
    protected function getDebugKey()
    {
        return 'fitch.manager.note';
    }
}
