<?php

namespace Fitch\TutorBundle\Model;

use Fitch\CommonBundle\Model\BaseModelManager;
use Fitch\TutorBundle\Entity\Repository\PhoneRepository;
use Fitch\TutorBundle\Entity\Phone;

class PhoneManager extends BaseModelManager implements PhoneManagerInterface
{
    /**
     * Create a new Phone.
     *
     * Set its default values
     *
     * @return Phone
     */
    public function createPhone()
    {
        return parent::createEntity();
    }

    /**
     * @param int $id
     */
    public function removePhone($id)
    {
        $phone = $this->findById($id);
        parent::removeEntity($phone);
    }

    /**
     * @param Phone $phone
     */
    public function refreshPhone(Phone $phone)
    {
        parent::reloadEntity($phone);
    }

    /**
     * @return PhoneRepository
     */
    private function getRepo()
    {
        return $this->repo;
    }

    /**
     * Used  to identify logs generated by this class.
     *
     * @return string
     */
    protected function getDebugKey()
    {
        return 'fitch.manager.phone';
    }
}
