<?php

namespace Fitch\TutorBundle\Model;

use Fitch\CommonBundle\Entity\NamedEntityInterface;
use Fitch\CommonBundle\Model\BaseModelManager;
use Fitch\TutorBundle\Entity\Proficiency;
use Fitch\TutorBundle\Model\Traits\DefaultEntityTrait;

/**
 * Class ProficiencyManager.
 */
class ProficiencyManager extends BaseModelManager implements ProficiencyManagerInterface
{
    use DefaultEntityTrait;

    /**
     * @param string $proficiencyName
     *
     * @return Proficiency
     */
    public function findOrCreate($proficiencyName)
    {
        $proficiency = $this->getRepo()->findOneBy(['name' => $proficiencyName]);

        if (!$proficiency) {
            $proficiency = $this->createEntity();
            $proficiency->setName($proficiencyName);
            $this->saveEntity($proficiency);
        }

        return $proficiency;
    }

    /**
     * Returns all active competencyLevels as a Array - suitable for use in "select"
     * style lists, with a grouped sections.
     *
     * (there's no obvious grouping, so its a flat list for Proficiency)
     *
     * @return array
     */
    public function buildGroupedChoices()
    {
        return parent::buildFlatChoices(function (NamedEntityInterface $entity) {
            return $entity->getName();
        });
    }

    /**
     * Used  to identify logs generated by this class.
     *
     * @return string
     */
    protected function getDebugKey()
    {
        return 'fitch.manager.proficiency';
    }
}
