<?php

namespace Fitch\TutorBundle\Model;

use Fitch\CommonBundle\Model\BaseModelManager;
use Fitch\TutorBundle\Entity\Repository\RateRepository;
use Fitch\TutorBundle\Entity\Rate;
use Gedmo\Loggable\Entity\Repository\LogEntryRepository;

class RateManager extends BaseModelManager implements RateManagerInterface
{
    /**
     * @return array
     */
    public function buildChoices()
    {
        $rateTypes = [];
        foreach ($this->getRepo()->getActiveRateTypes() as $rateType) {
            $rateTypes[$rateType['name']] = $rateType['name'];
        };

        return $rateTypes;
    }

    /**
     * @param Rate $rate
     *
     * @return array
     */
    public function getLogs(Rate $rate)
    {
        return $this->getLogEntryRepo()->getLogEntries($rate);
    }

    /**
     * @param int $id
     */
    public function removeEntity($id)
    {
        $rate = $this->findById($id);
        parent::removeEntity($rate);
    }

    /**
     * @return RateRepository
     */
    protected function getRepo()
    {
        return parent::getRepo();
    }

    /**
     * @return LogEntryRepository
     */
    private function getLogEntryRepo()
    {
        return $this->em->getRepository('Gedmo\Loggable\Entity\LogEntry');
    }

    /**
     * Used  to identify logs generated by this class.
     *
     * @return string
     */
    protected function getDebugKey()
    {
        return 'fitch.manager.rate';
    }
}
