<?php

namespace Fitch\TutorBundle\Model;

use Fitch\CommonBundle\Exception\EntityNotFoundException;
use Fitch\CommonBundle\Model\BaseModelManager;
use Fitch\TutorBundle\Entity\Repository\RateRepository;
use Fitch\TutorBundle\Entity\Rate;

class RateManager extends BaseModelManager
{
   /**
     * @param $id
     * @throws EntityNotFoundException
     * @return Rate
     */
    public function findById($id)
    {
        return parent::findById($id);
    }

    /**
     * @return Rate[]
     */
    public function findAll()
    {
        return parent::findAll();
    }

    /**
     * @param Rate $rate
     * @param bool $withFlush
     */
    public function saveRate($rate, $withFlush = true)
    {
        parent::saveEntity($rate, $withFlush);
    }

    /**
     * Create a new Rate
     *
     * Set its default values
     *
     * @return Rate
     */
    public function createRate()
    {
        return parent::createEntity();
    }

    /**
     * @param int $id
     */
    public function removeRate($id)
    {
        $rate = $this->findById($id);
        parent::removeEntity($rate);
    }

    /**
     * @param Rate $rate
     */
    public function refreshRate(Rate $rate)
    {
        parent::reloadEntity($rate);
    }

    /**
     * @return RateRepository
     */
    private function getRepo()
    {
        return $this->repo;
    }

    /**
     * Used  to identify logs generated by this class
     *
     * @return string
     */
    protected function getDebugKey()
    {
        return 'fitch.manager.rate';
    }
}
