<?php

namespace Fitch\TutorBundle\Model;

use Fitch\CommonBundle\Model\BaseModelManager;
use Fitch\TutorBundle\Entity\Repository\ReportRepository;
use Fitch\TutorBundle\Entity\Report;

class ReportManager extends BaseModelManager implements ReportManagerInterface
{
    /**
     * @param int $id
     */
    public function removeEntity($id)
    {
        $report = $this->findById($id);
        parent::removeEntity($report);
    }

    /**
     * Used  to identify logs generated by this class.
     *
     * @return string
     */
    protected function getDebugKey()
    {
        return 'fitch.manager.report';
    }
}
