<?php

namespace Fitch\TutorBundle\Model;

use Fitch\CommonBundle\Exception\EntityNotFoundException;
use Fitch\CommonBundle\Model\BaseModelManager;
use Fitch\TutorBundle\Entity\Repository\TutorRepository;
use Fitch\TutorBundle\Entity\Tutor;

class TutorManager extends BaseModelManager implements TutorManagerInterface
{
    /**
     * @param $id
     *
     * @throws EntityNotFoundException
     *
     * @return Tutor
     */
    public function findById($id)
    {
        return parent::findById($id);
    }

    /**
     * @return Tutor[]
     */
    public function findAll()
    {
        return parent::findAll();
    }

    /**
     * @return array
     */
    public function populateTable()
    {
        return $this->getRepo()->findAllForTable();
    }

    /**
     * @param ReportDefinition $definition
     *
     * @return Tutor[]
     */
    public function getReportData(ReportDefinition $definition)
    {
        return $this->getRepo()->getReportData($definition);
    }

    /**
     * @param Tutor                   $tutor
     * @param AddressManagerInterface $addressManager
     * @param CountryManagerInterface $countryManager
     */
    private function createDefaultAddressIfRequired(
        Tutor $tutor,
        AddressManagerInterface $addressManager,
        CountryManagerInterface $countryManager
    ) {
        if (!$tutor->hasAddress()) {
            $address = $addressManager->createAddress();
            $address->setCountry($countryManager->getDefaultCountry());
            $tutor->addAddress($address);
        }
    }

    /**
     * @param Tutor $tutor
     * @param bool  $withFlush
     */
    public function saveTutor($tutor, $withFlush = true)
    {
        parent::saveEntity($tutor, $withFlush);
    }

    /**
     * Create a new Tutor.
     *
     * Set its default values
     *
     * @param AddressManagerInterface         $addressManager
     * @param CountryManagerInterface         $countryManager
     * @param StatusManagerInterface          $statusManager
     * @param OperatingRegionManagerInterface $operatingRegionManager
     * @param TutorTypeManagerInterface       $tutorTypeManager
     *
     * @return Tutor
     */
    public function createTutor(
        AddressManagerInterface $addressManager,
        CountryManagerInterface $countryManager,
        StatusManagerInterface $statusManager,
        OperatingRegionManagerInterface $operatingRegionManager,
        TutorTypeManagerInterface $tutorTypeManager
    ) {
        /** @var Tutor $tutor */
        $tutor = parent::createEntity();
        $this->createDefaultAddressIfRequired($tutor, $addressManager, $countryManager);
        $this->setDefaultRegion($tutor, $operatingRegionManager);
        $this->setDefaultStatus($tutor, $statusManager);
        $this->setDefaultTutorType($tutor, $tutorTypeManager);

        return $tutor;
    }

    /**
     * @param Tutor                           $tutor
     * @param OperatingRegionManagerInterface $operatingRegionManager
     */
    private function setDefaultRegion(Tutor $tutor, OperatingRegionManagerInterface $operatingRegionManager)
    {
        $region = $operatingRegionManager->findDefaultOperatingRegion();
        if ($region) {
            $tutor->setRegion($region);
            $tutor->setCurrency($region->getDefaultCurrency());
        }
    }

    /**
     * @param Tutor                  $tutor
     * @param StatusManagerInterface $statusManager
     */
    private function setDefaultStatus(Tutor $tutor, StatusManagerInterface $statusManager)
    {
        $tutor->setStatus($statusManager->findDefaultStatus());
    }

    /**
     * @param Tutor                     $tutor
     * @param TutorTypeManagerInterface $tutorTypeManager
     */
    private function setDefaultTutorType(Tutor $tutor, TutorTypeManagerInterface $tutorTypeManager)
    {
        $tutor->setTutorType($tutorTypeManager->findDefaultTutorType());
    }

    /**
     * @param int $id
     */
    public function removeTutor($id)
    {
        $tutor = $this->findById($id);
        parent::removeEntity($tutor);
    }

    /**
     * @param Tutor $tutor
     */
    public function refreshTutor(Tutor $tutor)
    {
        parent::reloadEntity($tutor);
    }

    /**
     * @return TutorRepository
     */
    private function getRepo()
    {
        return $this->repo;
    }

    /**
     * Used  to identify logs generated by this class.
     *
     * @return string
     */
    protected function getDebugKey()
    {
        return 'fitch.manager.tutor';
    }
}
