<?php

namespace Fitch\TutorBundle\Model;

use Fitch\CommonBundle\Exception\EntityNotFoundException;
use Fitch\CommonBundle\Model\BaseModelManager;
use Fitch\TutorBundle\Entity\Repository\TutorLanguageRepository;
use Fitch\TutorBundle\Entity\TutorLanguage;

class TutorLanguageManager extends BaseModelManager
{
    /**
     * @param $id
     * @throws EntityNotFoundException
     * @return TutorLanguage
     */
    public function findById($id)
    {
        return parent::findById($id);
    }

    /**
     * @return TutorLanguage[]
     */
    public function findAll()
    {
        return parent::findAll();
    }

    /**
     * @param TutorLanguage $tutorLanguage
     * @param bool $withFlush
     */
    public function saveTutorLanguage($tutorLanguage, $withFlush = true)
    {
        parent::saveEntity($tutorLanguage, $withFlush);
    }

    /**
     * Create a new TutorLanguage
     *
     * Set its default values
     *
     * @return TutorLanguage
     */
    public function createTutorLanguage()
    {
        return parent::createEntity();
    }

    /**
     * @param int $id
     */
    public function removeTutorLanguage($id)
    {
        $tutorLanguage = $this->findById($id);
        parent::removeEntity($tutorLanguage);
    }

    /**
     * @param TutorLanguage $tutorLanguage
     */
    public function refreshTutorLanguage(TutorLanguage $tutorLanguage)
    {
        parent::reloadEntity($tutorLanguage);
    }

    /**
     * @return TutorLanguageRepository
     */
    private function getRepo()
    {
        return $this->repo;
    }

    /**
     * Used  to identify logs generated by this class
     *
     * @return string
     */
    protected function getDebugKey()
    {
        return 'fitch.manager.tutor_language';
    }
}
