<?php

namespace Fitch\EntityAttributeValueBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * This is the class that validates and merges configuration from the app/config files.
 *
 * @codeCoverageIgnore
 * (This is just a stub class generated by Symfony tools - dont think we need to test it unless it changes)
 */
class Configuration implements ConfigurationInterface
{
    /**
     * {@inheritDoc}
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $treeBuilder->root('fitch_eav');

        return $treeBuilder;
    }
}
